### ISSUE TITLE
FR: @bucket(method=True, ignore=['self'])

### ISSUE THREAD

**Issue by siebrenf** [RazerM/bucketcache#9]
Hi RazerM,

I'm not sure if the package is still maintained, but we've been using it in [genomepy](https://github.com/vanheeringen-lab/genomepy) for a while now and could use some quality of life changes!

When using the wrapper on a class method, `self` cannot be ignored. I've resorted to making all cached functions `staticmethods`, but this is not very pretty.

**Comment by RazerM** [comment]
I'm not actively maintaining it, but I'll accept PRs and push new releases if that helps!

I don't remember the details but I wonder if this would work: `@bucket(method=False, ignore=['self'])`. Of course all instances of your class would see the same cached results, so `staticmethod`s probably makes sense unless you need to do something with side effects like `self.log('downloading...')`

**Comment by siebrenf** [comment]
It works! Thanks :)

Also thanks for the warning, I'll take it along!
